// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaceCOayldyPZDh4_qhAnJsmEq_SXAUrY',
    appId: '1:1095935930094:web:0762d55bd5a36cffd28dff',
    messagingSenderId: '1095935930094',
    projectId: 'signalr-634ee',
    authDomain: 'signalr-634ee.firebaseapp.com',
    storageBucket: 'signalr-634ee.appspot.com',
    measurementId: 'G-LYP50PGCTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzYqASm3FnkvVGnVbFGE306IfiyPpt8Jg',
    appId: '1:1095935930094:android:9940169fcdf1c87ad28dff',
    messagingSenderId: '1095935930094',
    projectId: 'signalr-634ee',
    storageBucket: 'signalr-634ee.appspot.com',
  );
}
